// Generated by Tools/generate_catalog.py from GroupSlots. Do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once
#include <cstddef>
#include <iterator>

namespace lr608::generated
{
struct PageDescriptor
{
    const char* name;
    const char* const* parameterIds;
    const char* const* parameterNames;
    std::size_t parameterCount;
    int rowsPerColumn;
};

inline constexpr const char* page1Ids[] = { "routeKick", "slider011", "slider012", "slider013", "slider014", "slider015", "slider016", "slider017", "slider018", "slider067", "slider078", "slider079", "slider100", "slider101", "slider102", "slider103", "slider104", "slider105", "slider106", "slider107", "slider138", "slider140", "slider141", "slider142", "slider148", "slider149", "slider150", "slider151", "slider152", "slider153", "slider154", "slider155", "slider247" };
inline constexpr const char* page1Names[] = { "Kick Output", "Kick Level", "Kick Tune", "Kick Punch Amount", "Kick Punch Time", "Kick Decay", "Kick Curve", "Kick Click Level", "Kick Noise Tone", "Kick Click Phase", "Kick Curve Pitch", "Kick Curve Pitch Decay", "Kick Noise Decay", "Kick Noise Level", "Kick LFO Volume Depth", "Kick LFO Frequency", "Kick LFO Wave", "Kick LFO Pitch Depth", "Kick LFO Delay", "Kick Body Drive", "Kick Body Drive Mix", "Kick Body Phase", "Kick LFO Smooth", "Kick LFO Wave Shape", "Kick Click Tone", "Kick Click Resonance", "Kick Comp Threshold", "Kick Comp Ratio", "Kick Comp Gain", "Kick Comp Attack (ms)", "Kick Comp Release (ms)", "Kick Comp Mix", "Kick Engine" };
inline constexpr const char* page2Ids[] = { "routeSnare1", "slider019", "slider020", "slider021", "slider022", "slider023", "slider024", "slider025", "slider026", "slider027", "slider028", "slider029", "slider092", "slider094", "slider096", "slider098", "slider108", "slider116", "slider117", "slider132", "slider133", "slider134", "slider135", "slider136", "slider137", "slider139", "slider156", "slider157", "slider158", "slider159", "slider160", "slider161", "slider248" };
inline constexpr const char* page2Names[] = { "Snare 1 Output", "Snare Noise Tone Env", "Snare Level", "Snare Click Level", "Snare Body Decay", "Snare Body Tune", "Snare Body Level", "Snare Noise Decay", "Snare Noise Level", "Snare Noise Tone", "Snare Noise Resonance", "Snare Body Pitch Decay", "Snare Noise Attack", "Snare Noise Color", "Snare Noise Degrade", "Snare Filter Env Amount", "Snare Drive", "Snare Body Mid", "Snare Body High", "Snare Noise Ring Freq", "Snare Noise Ring Depth", "Snare Noise Ring Wave", "Snare Noise Ring Smooth", "Snare Noise Ring Delay", "Snare Noise Ring Wave Shape", "Snare Drive Mix", "Snare Comp Threshold", "Snare Comp Ratio", "Snare Comp Gain", "Snare Comp Attack (ms)", "Snare Comp Release (ms)", "Snare Comp Mix", "Snare 1 Engine" };
inline constexpr const char* page3Ids[] = { "routeSnare2", "slider198", "slider221", "slider225", "slider224", "slider223", "slider230", "slider232", "slider233", "slider222", "slider227", "slider226", "slider228", "slider229", "slider220", "slider093", "slider095", "slider097", "slider234", "slider236", "slider235", "slider237", "slider238", "slider239", "slider099", "slider231", "slider240", "slider241", "slider242", "slider243", "slider244", "slider245", "slider246" };
inline constexpr const char* page3Names[] = { "Snare 2 Output", "Snare 2 Engine", "Snare2 Level", "Snare2 Body Level", "Snare2 Body Tune", "Snare2 Body Decay", "Snare2 Body Pitch Decay", "Snare2 Body Mid", "Snare2 Body High", "Snare2 Click Level", "Snare2 Noise Level", "Snare2 Noise Decay", "Snare2 Noise Tone", "Snare2 Noise Resonance", "Snare2 Noise Tone Env", "Snare2 Noise Attack", "Snare2 Noise Color", "Snare2 Noise Degrade", "Snare2 Noise Ring Freq", "Snare2 Noise Ring Wave", "Snare2 Noise Ring Depth", "Snare2 Noise Ring Smooth", "Snare2 Noise Ring Delay", "Snare2 Noise Ring Wave Shape", "Snare2 Filter Env Amount", "Snare2 Drive", "Snare2 Drive Mix", "Snare2 Comp Threshold", "Snare2 Comp Ratio", "Snare2 Comp Gain", "Snare2 Comp Attack (ms)", "Snare2 Comp Release (ms)", "Snare2 Comp Mix" };
inline constexpr const char* page4Ids[] = { "routeClap", "slider030", "slider031", "slider032", "slider033", "slider034", "slider035", "slider036", "slider037", "slider038", "slider039", "slider207", "slider208" };
inline constexpr const char* page4Names[] = { "Clap Output", "Clap Level", "Clap Decay", "Clap Tone", "Clap Hit Level", "Clap Filter Tone", "Clap Character", "Clap Filter Decay Follow", "Clap Sequence Balance", "Clap Body Size", "Clap Dirt", "Clap Engine", "Clap Resonance" };
inline constexpr const char* page5Ids[] = { "routeRim", "slider068", "slider069", "slider070", "slider071", "slider124", "slider125", "slider143", "slider144", "slider145", "slider146", "slider147", "slider162", "slider163", "slider164", "slider165", "slider166", "slider167", "slider209", "slider252" };
inline constexpr const char* page5Names[] = { "Rim Output", "Rim Click Level", "Rim Tone", "Rim Decay", "Rim Level", "Rim Second Mode Level", "Rim Second Mode Tune", "Rim Tape Delay Mix", "Rim Tape Delay Time", "Rim Tape Delay Tone", "Rim Tape Delay Resonance", "Rim Tape Delay Feedback", "Rim Comp Threshold", "Rim Comp Ratio", "Rim Comp Gain", "Rim Comp Attack (ms)", "Rim Comp Release (ms)", "Rim Comp Mix", "Rim Engine", "Rim Delay Mode" };
inline constexpr const char* page6Ids[] = { "routeLowTom", "routeMidTom", "routeHighTom", "slider040", "slider041", "slider042", "slider043", "slider044", "slider045", "slider046", "slider047", "slider048", "slider049", "slider050", "slider051", "slider052", "slider053", "slider054", "slider055", "slider056", "slider057", "slider058", "slider059", "slider060", "slider061", "slider062", "slider063", "slider064", "slider065", "slider066", "slider109", "slider110", "slider111", "slider118", "slider119", "slider120", "slider121", "slider122", "slider123", "slider174", "slider175", "slider176", "slider177", "slider178", "slider179", "slider180", "slider181", "slider182", "slider183", "slider184", "slider185", "slider186", "slider187", "slider188", "slider189", "slider190", "slider191", "slider219" };
inline constexpr const char* page6Names[] = { "Low Tom Output", "Mid Tom Output", "High Tom Output", "Low Tom Pan", "Low Tom Click Level", "Low Tom Tune", "Low Tom Pitch Decay", "Low Tom Pitch Amount", "Low Tom Decay", "Low Tom Noise Level", "Low Tom Noise LPF", "Mid Tom Pan", "Mid Tom Click Level", "Mid Tom Tune", "Mid Tom Pitch Decay", "Mid Tom Pitch Amount", "Mid Tom Decay", "Mid Tom Noise Level", "Mid Tom Noise LPF", "High Tom Pan", "High Tom Click Level", "High Tom Tune", "High Tom Pitch Decay", "High Tom Pitch Amount", "High Tom Decay", "High Tom Noise Level", "High Tom Noise LPF", "Low Tom Level", "Mid Tom Level", "High Tom Level", "Low Tom Wave Morph", "Mid Tom Wave Morph", "High Tom Wave Morph", "Low Tom Saturation", "Mid Tom Saturation", "High Tom Saturation", "Low Tom Noise Decay", "Mid Tom Noise Decay", "High Tom Noise Decay", "LowTom Comp Threshold", "LowTom Comp Ratio", "LowTom Comp Gain", "LowTom Comp Attack (ms)", "LowTom Comp Release (ms)", "LowTom Comp Mix", "MidTom Comp Threshold", "MidTom Comp Ratio", "MidTom Comp Gain", "MidTom Comp Attack (ms)", "MidTom Comp Release (ms)", "MidTom Comp Mix", "HighTom Comp Threshold", "HighTom Comp Ratio", "HighTom Comp Gain", "HighTom Comp Attack (ms)", "HighTom Comp Release (ms)", "HighTom Comp Mix", "Toms Engine" };
inline constexpr const char* page7Ids[] = { "routeHiHat", "slider001", "slider002", "slider003", "slider004", "slider005", "slider090", "slider091", "slider114", "slider115", "slider217", "slider218" };
inline constexpr const char* page7Names[] = { "HiHat Output", "HiHat CH Decay", "HiHat OH Decay", "HiHat Brightness", "HiHat Metal", "HiHat Level", "HiHat Resonance Mod Amount", "HiHat Resonance Mod Speed (Hz)", "HiHat Metal2", "HiHat Tune", "HiHat Engine", "HiHat Structure" };
inline constexpr const char* page8Ids[] = { "routeCrash", "routeRide", "slider006", "slider007", "slider008", "slider009", "slider010", "slider112", "slider113", "slider214" };
inline constexpr const char* page8Names[] = { "Crash Output", "Ride Output", "Crash Decay", "Ride Decay", "Cymbal Brightness", "Crash Level", "Ride Level", "Ride Pitch Relax", "Ride Relax Speed", "Cymbal Engine" };
inline constexpr const char* page9Ids[] = { "routeMaracas", "slider168", "slider169", "slider170", "slider171", "slider172", "slider173", "slider205", "slider206", "slider216" };
inline constexpr const char* page9Names[] = { "Maracas Output", "Maracas Level", "Maracas Attack", "Maracas Decay", "Maracas Noise Color", "Maracas S&H Rate", "Maracas S&H Amount", "Maracas Bounce", "Maracas Ghost Softness", "Maracas Engine" };
inline constexpr const char* page10Ids[] = { "routeCowbell", "slider080", "slider081", "slider082", "slider083", "slider084", "slider085", "slider086", "slider087", "slider088", "slider089", "slider204", "slider215" };
inline constexpr const char* page10Names[] = { "Clave/Cowbell Output", "Clave/Cowbell Level", "Clave/Cowbell Decay", "Clave/Cowbell Base Pitch", "Clave/Cowbell Inharmonic Ratio", "Clave/Cowbell Click Amount", "Clave/Cowbell Click Sharpness", "Clave/Cowbell Metal Body Balance", "Clave/Cowbell Ring Mod Amount", "Clave/Cowbell Accent Bite", "Clave/Cowbell Pitch Snap Amount", "Clave/Cowbell Saturation Mix", "Cowbell Engine" };
inline constexpr const char* page11Ids[] = { "routeZap", "slider072", "slider073", "slider074", "slider075", "slider076", "slider077", "slider126", "slider127", "slider128", "slider129", "slider130", "slider131", "slider192", "slider193", "slider194", "slider195", "slider196", "slider197", "slider199", "slider210", "slider211", "slider212", "slider213" };
inline constexpr const char* page11Names[] = { "Zap Output", "Zap Level", "Zap Fast Decay", "Zap Slow Decay", "Zap Curve", "Zap Tune", "Zap Click Level", "ZAP LFO Frequency", "ZAP LFO Pitch Depth", "ZAP LFO Wave", "ZAP LFO Smooth", "ZAP LFO Delay", "ZAP LFO Wave Shape", "Zap Comp Threshold", "Zap Comp Ratio", "Zap Comp Gain", "Zap Comp Attack (ms)", "Zap Comp Release (ms)", "Zap Comp Mix", "Zap Engine", "Zap Ring Mix", "Zap Ring Frequency", "Zap Ring Wave", "Zap Ring Env Freq Mod" };
inline constexpr const char* page12Ids[] = { "slider249", "slider253", "slider254", "slider250", "slider251", "slider256" };
inline constexpr const char* page12Names[] = { "Roll Division", "Roll Shuffle", "Roll Second Hit Velocity Reduction", "Accent Velocity Threshold", "Accent Character", "Master Volume (dB)" };

inline constexpr PageDescriptor pages[] = {
    { "Kick", page1Ids, page1Names, std::size (page1Ids), 8 },
    { "Snare 1", page2Ids, page2Names, std::size (page2Ids), 8 },
    { "Snare 2", page3Ids, page3Names, std::size (page3Ids), 8 },
    { "Clap", page4Ids, page4Names, std::size (page4Ids), 6 },
    { "Rim", page5Ids, page5Names, std::size (page5Ids), 10 },
    { "Toms", page6Ids, page6Names, std::size (page6Ids), 8 },
    { "HiHat", page7Ids, page7Names, std::size (page7Ids), 11 },
    { "Cymbal", page8Ids, page8Names, std::size (page8Ids), 8 },
    { "Maracas", page9Ids, page9Names, std::size (page9Ids), 9 },
    { "Clave / Cowbell", page10Ids, page10Names, std::size (page10Ids), 6 },
    { "Zap", page11Ids, page11Names, std::size (page11Ids), 9 },
    { "Global", page12Ids, page12Names, std::size (page12Ids), 4 },
};
}
